services:
  nginx:
    #this is very explicit for understanding, it could also just be build: requirements/nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    #restarts when the container crashes
    restart: unless-stopped
    networks:
      - inception-network
    # see https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
    volumes:
      #this links the actual location "/root/data" to the container location "/var/www/"
      #root because docker compose gets called using sudo
      - ${DATA_FOLDER}:/var/www/
    #TODO: figure out if ports is needed
    ports:
      - "443:443"

#the network shown in the subject diagram
networks:
  inception-network:
    name: inception-network

#   frontend:
#     image: awesome/webapp
#     ports:
#       - "443:8043"
#     networks:
#       - front-tier
#       - back-tier
#     configs:
#       - httpd-config
#     secrets:
#       - server-certificate

#   backend:
#     image: awesome/database
#     volumes:
#       - db-data:/etc/data
#     networks:
#       - back-tier

# volumes:
#   db-data:
#     driver: flocker
#     driver_opts:
#       size: "10GiB"

# configs:
#   httpd-config:
#     external: true

# secrets:
#   server-certificate:
#     external: true

# networks:
#   # The presence of these objects is sufficient to define them
#   front-tier: {}
#   back-tier: {}