version: "3"

services:
  nginx:
    #it will only start after wordpress is up
    depends_on:
      - wordpress

    #this is very explicit for understanding, it could also just be build: requirements/nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile

    #restarts when the container crashes
    restart: unless-stopped

    networks:
      - inception-network

    #makes the service use a volume when accessing files at the /var/www/html/ path
    #so that any files in there are persistent between sessions
    volumes:
      - wp-volume:/var/www/html/

    #host_port:port_within_container
    ports:
      - "443:443"

    #to prevent zombie processes
    init: true


  mariadb:

    build:
      context: requirements/mariadb
      dockerfile: Dockerfile

    restart: unless-stopped

    networks:
      - inception-network

    volumes:
      - db-volume:/var/lib/mysql

    init: true

    #specify what environment variables to use
    env_file: .env

    #locally define environment variables
    environment:
      - MYSQL_DATABASE=wordpress


  wordpress:
    depends_on:
      - mariadb

    build:
      context: requirements/wordpress
      dockerfile: Dockerfile

    restart: unless-stopped

    networks:
      - inception-network

    volumes:
      - wp-volume:/var/www/html/

    init: true

    env_file: .env

    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress


#the network shown in the subject diagram
networks:
  inception-network:
    name: inception-network


#the volumes shown in the subject diagram
volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pdruart/data/wordpress/

  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pdruart/data/mariadb/
