services:
  nginx:
    #it will only start after wordpress is up
    depends_on:
      - wordpress

    #this is very explicit for understanding, it could also just be build: requirements/nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile

    #restarts when the container crashes
    restart: unless-stopped

    networks:
      - inception-network

    #makes the service use a volume when accessing files at the /var/www/ path
    #so that any files in there are persistent between sessions
    volumes:
      - wp-volume:/var/www/

    #host_port:port_within_container
    ports:
      - "443:443"

    #to prevent zombie processes
    init: true


  mariadb:

    build:
      context: requirements/mariadb
      dockerfile: Dockerfile

    restart: unless-stopped

    networks:
      - inception-network

    volumes:
      - db-volume:/var/lib/mysql

    init: true
    #commented out cause this should get automatically loaded from the .env file but testing might prove me wrong
    # environment: #just for clarification, this isn't actual credentials, just examples
    #   MYSQL_ROOT_PASSWORD: rootpress
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: wordpress
    #   MYSQL_PASSWORD: wordpress


  wordpress:
    depends_on:
      - mariadb

    build:
      context: requirements/wordpress
      dockerfile: Dockerfile

    restart: unless-stopped

    networks:
      - inception-network

    volumes:
      - wp-volume:/var/www/

    init: true


#the network shown in the subject diagram
networks:
  inception-network:
    name: inception-network


#the volumes shown in the subject diagram
volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pdruart/data

  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pdruart/data
