services:
  nginx:
    #this is very explicit for understanding, it could also just be build: requirements/nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    #restarts when the container crashes
    restart: unless-stopped
    networks:
      - inception-network
    #makes the service use a volume when accessing files at the /var/www/ path
    #so that any files in there are persistent between sessions
    volumes:
      - wp-volume:/var/www/
    #host_port:port_within_container
    ports:
      - "443:443"

#the network shown in the subject diagram
networks:
  inception-network:
    name: inception-network

#the volumes shown in the subject diagram
volumes:
  wp-volume:
  db-volume:


#   frontend:
#     image: awesome/webapp
#     ports:
#       - "443:8043"
#     networks:
#       - front-tier
#       - back-tier
#     configs:
#       - httpd-config
#     secrets:
#       - server-certificate

#   backend:
#     image: awesome/database
#     volumes:
#       - db-data:/etc/data
#     networks:
#       - back-tier

# volumes:
#   db-data:
#     driver: flocker
#     driver_opts:
#       size: "10GiB"

# configs:
#   httpd-config:
#     external: true

# secrets:
#   server-certificate:
#     external: true

# networks:
#   # The presence of these objects is sufficient to define them
#   front-tier: {}
#   back-tier: {}