FROM alpine:3.17

RUN apk update
#??? can't find something like apk add wordpress
	#&& \
	# apk add mariadb mariadb-client

WORKDIR /tmp/wordpress/

# COPY conf/ ${WORKDIR}

#??

EXPOSE 9000

#CMD mysqld
